# CMake generated Testfile for 
# Source directory: C:/dev/URPG Maker
# Build directory: C:/dev/URPG Maker/build-local
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("C:/dev/URPG Maker/build-local/urpg_tests-b12d07c_include.cmake")
include("C:/dev/URPG Maker/build-local/urpg_integration_tests-b12d07c_include.cmake")
include("C:/dev/URPG Maker/build-local/urpg_snapshot_tests-b12d07c_include.cmake")
include("C:/dev/URPG Maker/build-local/urpg_compat_tests-b12d07c_include.cmake")
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_snapshot_regression_lane]=] "C:/dev/URPG Maker/build-local/Debug/urpg_snapshot_tests.exe" "[snapshot][regression]")
  set_tests_properties([=[urpg_snapshot_regression_lane]=] PROPERTIES  LABELS "nightly;regression" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1533;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_snapshot_regression_lane]=] "C:/dev/URPG Maker/build-local/Release/urpg_snapshot_tests.exe" "[snapshot][regression]")
  set_tests_properties([=[urpg_snapshot_regression_lane]=] PROPERTIES  LABELS "nightly;regression" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1533;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_snapshot_regression_lane]=] "C:/dev/URPG Maker/build-local/MinSizeRel/urpg_snapshot_tests.exe" "[snapshot][regression]")
  set_tests_properties([=[urpg_snapshot_regression_lane]=] PROPERTIES  LABELS "nightly;regression" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1533;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_snapshot_regression_lane]=] "C:/dev/URPG Maker/build-local/RelWithDebInfo/urpg_snapshot_tests.exe" "[snapshot][regression]")
  set_tests_properties([=[urpg_snapshot_regression_lane]=] PROPERTIES  LABELS "nightly;regression" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1533;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_snapshot_regression_lane]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_exported_runtime_smoke]=] "C:/dev/URPG Maker/build-local/Debug/urpg_integration_tests.exe" "[export][runtime_smoke]")
  set_tests_properties([=[urpg_exported_runtime_smoke]=] PROPERTIES  LABELS "nightly;export" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1542;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_exported_runtime_smoke]=] "C:/dev/URPG Maker/build-local/Release/urpg_integration_tests.exe" "[export][runtime_smoke]")
  set_tests_properties([=[urpg_exported_runtime_smoke]=] PROPERTIES  LABELS "nightly;export" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1542;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_exported_runtime_smoke]=] "C:/dev/URPG Maker/build-local/MinSizeRel/urpg_integration_tests.exe" "[export][runtime_smoke]")
  set_tests_properties([=[urpg_exported_runtime_smoke]=] PROPERTIES  LABELS "nightly;export" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1542;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_exported_runtime_smoke]=] "C:/dev/URPG Maker/build-local/RelWithDebInfo/urpg_integration_tests.exe" "[export][runtime_smoke]")
  set_tests_properties([=[urpg_exported_runtime_smoke]=] PROPERTIES  LABELS "nightly;export" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1542;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_exported_runtime_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_audio_preprocessing_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/audio/tests/test_audio_preprocessing_acceptance.py")
  set_tests_properties([=[urpg_audio_preprocessing_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1571;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_audio_preprocessing_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/audio/tests/test_audio_preprocessing_acceptance.py")
  set_tests_properties([=[urpg_audio_preprocessing_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1571;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_audio_preprocessing_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/audio/tests/test_audio_preprocessing_acceptance.py")
  set_tests_properties([=[urpg_audio_preprocessing_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1571;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_audio_preprocessing_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/audio/tests/test_audio_preprocessing_acceptance.py")
  set_tests_properties([=[urpg_audio_preprocessing_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1571;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_audio_preprocessing_acceptance_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_retrieval_artifact_contracts_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_artifact_contracts.py")
  set_tests_properties([=[urpg_retrieval_artifact_contracts_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1575;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_retrieval_artifact_contracts_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_artifact_contracts.py")
  set_tests_properties([=[urpg_retrieval_artifact_contracts_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1575;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_retrieval_artifact_contracts_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_artifact_contracts.py")
  set_tests_properties([=[urpg_retrieval_artifact_contracts_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1575;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_retrieval_artifact_contracts_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_artifact_contracts.py")
  set_tests_properties([=[urpg_retrieval_artifact_contracts_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1575;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_retrieval_artifact_contracts_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_retrieval_adapter_resolution_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_build_retrieval_bundle.py")
  set_tests_properties([=[urpg_retrieval_adapter_resolution_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1579;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_retrieval_adapter_resolution_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_build_retrieval_bundle.py")
  set_tests_properties([=[urpg_retrieval_adapter_resolution_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1579;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_retrieval_adapter_resolution_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_build_retrieval_bundle.py")
  set_tests_properties([=[urpg_retrieval_adapter_resolution_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1579;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_retrieval_adapter_resolution_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_build_retrieval_bundle.py")
  set_tests_properties([=[urpg_retrieval_adapter_resolution_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1579;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_retrieval_adapter_resolution_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_retrieval_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_retrieval_acceptance.py")
  set_tests_properties([=[urpg_retrieval_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1583;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_retrieval_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_retrieval_acceptance.py")
  set_tests_properties([=[urpg_retrieval_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1583;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_retrieval_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_retrieval_acceptance.py")
  set_tests_properties([=[urpg_retrieval_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1583;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_retrieval_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/retrieval/tests/test_retrieval_acceptance.py")
  set_tests_properties([=[urpg_retrieval_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1583;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_retrieval_acceptance_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_vision_segmentation_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/vision/tests/test_segmentation_acceptance.py")
  set_tests_properties([=[urpg_vision_segmentation_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1587;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_vision_segmentation_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/vision/tests/test_segmentation_acceptance.py")
  set_tests_properties([=[urpg_vision_segmentation_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1587;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_vision_segmentation_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/vision/tests/test_segmentation_acceptance.py")
  set_tests_properties([=[urpg_vision_segmentation_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1587;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_vision_segmentation_acceptance_test]=] "C:/Users/Doc/AppData/Local/Python/pythoncore-3.14-64/python.exe" "tools/vision/tests/test_segmentation_acceptance.py")
  set_tests_properties([=[urpg_vision_segmentation_acceptance_test]=] PROPERTIES  LABELS "pr;tools;python" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1560;add_test;C:/dev/URPG Maker/CMakeLists.txt;1587;urpg_add_python_tool_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_vision_segmentation_acceptance_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_editor_smoke]=] "C:/dev/URPG Maker/build-local/Debug/urpg_editor.exe" "--smoke" "--headless" "--project-root" "C:/dev/URPG Maker/content/fixtures/editor_smoke_project" "--smoke-output" "C:/dev/URPG Maker/build-local/editor_smoke/editor_state.json" "--smoke-snapshot-root" "C:/dev/URPG Maker/build-local/editor_smoke/snapshots")
  set_tests_properties([=[urpg_editor_smoke]=] PROPERTIES  LABELS "pr;editor_smoke" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1601;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_editor_smoke]=] "C:/dev/URPG Maker/build-local/Release/urpg_editor.exe" "--smoke" "--headless" "--project-root" "C:/dev/URPG Maker/content/fixtures/editor_smoke_project" "--smoke-output" "C:/dev/URPG Maker/build-local/editor_smoke/editor_state.json" "--smoke-snapshot-root" "C:/dev/URPG Maker/build-local/editor_smoke/snapshots")
  set_tests_properties([=[urpg_editor_smoke]=] PROPERTIES  LABELS "pr;editor_smoke" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1601;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_editor_smoke]=] "C:/dev/URPG Maker/build-local/MinSizeRel/urpg_editor.exe" "--smoke" "--headless" "--project-root" "C:/dev/URPG Maker/content/fixtures/editor_smoke_project" "--smoke-output" "C:/dev/URPG Maker/build-local/editor_smoke/editor_state.json" "--smoke-snapshot-root" "C:/dev/URPG Maker/build-local/editor_smoke/snapshots")
  set_tests_properties([=[urpg_editor_smoke]=] PROPERTIES  LABELS "pr;editor_smoke" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1601;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_editor_smoke]=] "C:/dev/URPG Maker/build-local/RelWithDebInfo/urpg_editor.exe" "--smoke" "--headless" "--project-root" "C:/dev/URPG Maker/content/fixtures/editor_smoke_project" "--smoke-output" "C:/dev/URPG Maker/build-local/editor_smoke/editor_state.json" "--smoke-snapshot-root" "C:/dev/URPG Maker/build-local/editor_smoke/snapshots")
  set_tests_properties([=[urpg_editor_smoke]=] PROPERTIES  LABELS "pr;editor_smoke" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1601;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_editor_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_editor_list_panels]=] "C:/dev/URPG Maker/build-local/Debug/urpg_editor.exe" "--headless" "--list-panels" "--frames" "1")
  set_tests_properties([=[urpg_editor_list_panels]=] PROPERTIES  LABELS "pr;editor_smoke" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1620;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_editor_list_panels]=] "C:/dev/URPG Maker/build-local/Release/urpg_editor.exe" "--headless" "--list-panels" "--frames" "1")
  set_tests_properties([=[urpg_editor_list_panels]=] PROPERTIES  LABELS "pr;editor_smoke" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1620;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_editor_list_panels]=] "C:/dev/URPG Maker/build-local/MinSizeRel/urpg_editor.exe" "--headless" "--list-panels" "--frames" "1")
  set_tests_properties([=[urpg_editor_list_panels]=] PROPERTIES  LABELS "pr;editor_smoke" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1620;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_editor_list_panels]=] "C:/dev/URPG Maker/build-local/RelWithDebInfo/urpg_editor.exe" "--headless" "--list-panels" "--frames" "1")
  set_tests_properties([=[urpg_editor_list_panels]=] PROPERTIES  LABELS "pr;editor_smoke" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1620;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_editor_list_panels]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_golden_replay_lane]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_golden_replays.ps1" "-RepoRoot" "C:/dev/URPG Maker")
  set_tests_properties([=[urpg_golden_replay_lane]=] PROPERTIES  LABELS "pr;replay" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1636;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_golden_replay_lane]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_golden_replays.ps1" "-RepoRoot" "C:/dev/URPG Maker")
  set_tests_properties([=[urpg_golden_replay_lane]=] PROPERTIES  LABELS "pr;replay" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1636;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_golden_replay_lane]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_golden_replays.ps1" "-RepoRoot" "C:/dev/URPG Maker")
  set_tests_properties([=[urpg_golden_replay_lane]=] PROPERTIES  LABELS "pr;replay" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1636;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_golden_replay_lane]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_golden_replays.ps1" "-RepoRoot" "C:/dev/URPG Maker")
  set_tests_properties([=[urpg_golden_replay_lane]=] PROPERTIES  LABELS "pr;replay" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1636;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_golden_replay_lane]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_install_smoke]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_install_smoke.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local" "-InstallPrefix" "C:/dev/URPG Maker/build-local/install-smoke")
  set_tests_properties([=[urpg_install_smoke]=] PROPERTIES  LABELS "nightly;packaging;install" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1654;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_install_smoke]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_install_smoke.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local" "-InstallPrefix" "C:/dev/URPG Maker/build-local/install-smoke")
  set_tests_properties([=[urpg_install_smoke]=] PROPERTIES  LABELS "nightly;packaging;install" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1654;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_install_smoke]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_install_smoke.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local" "-InstallPrefix" "C:/dev/URPG Maker/build-local/install-smoke")
  set_tests_properties([=[urpg_install_smoke]=] PROPERTIES  LABELS "nightly;packaging;install" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1654;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_install_smoke]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_install_smoke.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local" "-InstallPrefix" "C:/dev/URPG Maker/build-local/install-smoke")
  set_tests_properties([=[urpg_install_smoke]=] PROPERTIES  LABELS "nightly;packaging;install" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1654;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_install_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_package_smoke]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_package_smoke.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local" "-PackageRoot" "C:/dev/URPG Maker/build-local/package-smoke")
  set_tests_properties([=[urpg_package_smoke]=] PROPERTIES  LABELS "nightly;packaging" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1676;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_package_smoke]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_package_smoke.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local" "-PackageRoot" "C:/dev/URPG Maker/build-local/package-smoke")
  set_tests_properties([=[urpg_package_smoke]=] PROPERTIES  LABELS "nightly;packaging" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1676;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_package_smoke]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_package_smoke.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local" "-PackageRoot" "C:/dev/URPG Maker/build-local/package-smoke")
  set_tests_properties([=[urpg_package_smoke]=] PROPERTIES  LABELS "nightly;packaging" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1676;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_package_smoke]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/ci/check_package_smoke.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local" "-PackageRoot" "C:/dev/URPG Maker/build-local/package-smoke")
  set_tests_properties([=[urpg_package_smoke]=] PROPERTIES  LABELS "nightly;packaging" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1676;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_package_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_agent_knowledge_check]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/docs/check-agent-knowledge.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local")
  set_tests_properties([=[urpg_agent_knowledge_check]=] PROPERTIES  LABELS "pr;docs;agent" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1698;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_agent_knowledge_check]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/docs/check-agent-knowledge.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local")
  set_tests_properties([=[urpg_agent_knowledge_check]=] PROPERTIES  LABELS "pr;docs;agent" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1698;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_agent_knowledge_check]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/docs/check-agent-knowledge.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local")
  set_tests_properties([=[urpg_agent_knowledge_check]=] PROPERTIES  LABELS "pr;docs;agent" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1698;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_agent_knowledge_check]=] "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/dev/URPG Maker/tools/docs/check-agent-knowledge.ps1" "-RepoRoot" "C:/dev/URPG Maker" "-BuildDirectory" "C:/dev/URPG Maker/build-local")
  set_tests_properties([=[urpg_agent_knowledge_check]=] PROPERTIES  LABELS "pr;docs;agent" WORKING_DIRECTORY "C:/dev/URPG Maker" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1698;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_agent_knowledge_check]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_presentation_unit_lane]=] "C:/dev/URPG Maker/build-local/Debug/urpg_tests.exe" "[presentation]")
  set_tests_properties([=[urpg_presentation_unit_lane]=] PROPERTIES  LABELS "pr;presentation" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1721;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_presentation_unit_lane]=] "C:/dev/URPG Maker/build-local/Release/urpg_tests.exe" "[presentation]")
  set_tests_properties([=[urpg_presentation_unit_lane]=] PROPERTIES  LABELS "pr;presentation" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1721;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_presentation_unit_lane]=] "C:/dev/URPG Maker/build-local/MinSizeRel/urpg_tests.exe" "[presentation]")
  set_tests_properties([=[urpg_presentation_unit_lane]=] PROPERTIES  LABELS "pr;presentation" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1721;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_presentation_unit_lane]=] "C:/dev/URPG Maker/build-local/RelWithDebInfo/urpg_tests.exe" "[presentation]")
  set_tests_properties([=[urpg_presentation_unit_lane]=] PROPERTIES  LABELS "pr;presentation" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1721;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_presentation_unit_lane]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_spatial_editor_lane]=] "C:/dev/URPG Maker/build-local/Debug/urpg_tests.exe" "[editor][spatial]")
  set_tests_properties([=[urpg_spatial_editor_lane]=] PROPERTIES  LABELS "pr;presentation;editor" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1730;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_spatial_editor_lane]=] "C:/dev/URPG Maker/build-local/Release/urpg_tests.exe" "[editor][spatial]")
  set_tests_properties([=[urpg_spatial_editor_lane]=] PROPERTIES  LABELS "pr;presentation;editor" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1730;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_spatial_editor_lane]=] "C:/dev/URPG Maker/build-local/MinSizeRel/urpg_tests.exe" "[editor][spatial]")
  set_tests_properties([=[urpg_spatial_editor_lane]=] PROPERTIES  LABELS "pr;presentation;editor" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1730;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_spatial_editor_lane]=] "C:/dev/URPG Maker/build-local/RelWithDebInfo/urpg_tests.exe" "[editor][spatial]")
  set_tests_properties([=[urpg_spatial_editor_lane]=] PROPERTIES  LABELS "pr;presentation;editor" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1730;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_spatial_editor_lane]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_grid_part_unit_lane]=] "C:/dev/URPG Maker/build-local/Debug/urpg_tests.exe" "[grid_part]")
  set_tests_properties([=[urpg_grid_part_unit_lane]=] PROPERTIES  LABELS "pr;grid_part" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1739;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_grid_part_unit_lane]=] "C:/dev/URPG Maker/build-local/Release/urpg_tests.exe" "[grid_part]")
  set_tests_properties([=[urpg_grid_part_unit_lane]=] PROPERTIES  LABELS "pr;grid_part" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1739;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_grid_part_unit_lane]=] "C:/dev/URPG Maker/build-local/MinSizeRel/urpg_tests.exe" "[grid_part]")
  set_tests_properties([=[urpg_grid_part_unit_lane]=] PROPERTIES  LABELS "pr;grid_part" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1739;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_grid_part_unit_lane]=] "C:/dev/URPG Maker/build-local/RelWithDebInfo/urpg_tests.exe" "[grid_part]")
  set_tests_properties([=[urpg_grid_part_unit_lane]=] PROPERTIES  LABELS "pr;grid_part" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1739;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_grid_part_unit_lane]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_grid_part_integration_lane]=] "C:/dev/URPG Maker/build-local/Debug/urpg_integration_tests.exe" "[grid_part]")
  set_tests_properties([=[urpg_grid_part_integration_lane]=] PROPERTIES  LABELS "nightly;grid_part" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1748;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_grid_part_integration_lane]=] "C:/dev/URPG Maker/build-local/Release/urpg_integration_tests.exe" "[grid_part]")
  set_tests_properties([=[urpg_grid_part_integration_lane]=] PROPERTIES  LABELS "nightly;grid_part" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1748;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_grid_part_integration_lane]=] "C:/dev/URPG Maker/build-local/MinSizeRel/urpg_integration_tests.exe" "[grid_part]")
  set_tests_properties([=[urpg_grid_part_integration_lane]=] PROPERTIES  LABELS "nightly;grid_part" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1748;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_grid_part_integration_lane]=] "C:/dev/URPG Maker/build-local/RelWithDebInfo/urpg_integration_tests.exe" "[grid_part]")
  set_tests_properties([=[urpg_grid_part_integration_lane]=] PROPERTIES  LABELS "nightly;grid_part" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1748;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_grid_part_integration_lane]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_presentation_release_validation]=] "C:/dev/URPG Maker/build-local/Debug/urpg_presentation_release_validation.exe")
  set_tests_properties([=[urpg_presentation_release_validation]=] PROPERTIES  LABELS "nightly;presentation" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1758;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_presentation_release_validation]=] "C:/dev/URPG Maker/build-local/Release/urpg_presentation_release_validation.exe")
  set_tests_properties([=[urpg_presentation_release_validation]=] PROPERTIES  LABELS "nightly;presentation" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1758;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_presentation_release_validation]=] "C:/dev/URPG Maker/build-local/MinSizeRel/urpg_presentation_release_validation.exe")
  set_tests_properties([=[urpg_presentation_release_validation]=] PROPERTIES  LABELS "nightly;presentation" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1758;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_presentation_release_validation]=] "C:/dev/URPG Maker/build-local/RelWithDebInfo/urpg_presentation_release_validation.exe")
  set_tests_properties([=[urpg_presentation_release_validation]=] PROPERTIES  LABELS "nightly;presentation" _BACKTRACE_TRIPLES "C:/dev/URPG Maker/CMakeLists.txt;1758;add_test;C:/dev/URPG Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_presentation_release_validation]=] NOT_AVAILABLE)
endif()
subdirs("_deps/catch2-build")
subdirs("_deps/nlohmann_json-build")
subdirs("_deps/quickjs_ng-build")
subdirs("_deps/sdl2-build")
