# CMake generated Testfile for 
# Source directory: C:/Users/dferr/dev/URPG - RPG Game Maker
# Build directory: C:/Users/dferr/dev/URPG - RPG Game Maker/build-local
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/urpg_tests-b12d07c_include.cmake")
include("C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/urpg_integration_tests-b12d07c_include.cmake")
include("C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/urpg_snapshot_tests-b12d07c_include.cmake")
include("C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/urpg_compat_tests-b12d07c_include.cmake")
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_presentation_release_validation]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/Debug/urpg_presentation_release_validation.exe")
  set_tests_properties([=[urpg_presentation_release_validation]=] PROPERTIES  LABELS "nightly;presentation" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;389;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_presentation_release_validation]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/Release/urpg_presentation_release_validation.exe")
  set_tests_properties([=[urpg_presentation_release_validation]=] PROPERTIES  LABELS "nightly;presentation" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;389;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_presentation_release_validation]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/MinSizeRel/urpg_presentation_release_validation.exe")
  set_tests_properties([=[urpg_presentation_release_validation]=] PROPERTIES  LABELS "nightly;presentation" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;389;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_presentation_release_validation]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/RelWithDebInfo/urpg_presentation_release_validation.exe")
  set_tests_properties([=[urpg_presentation_release_validation]=] PROPERTIES  LABELS "nightly;presentation" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;389;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_presentation_release_validation]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_presentation_unit_lane]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/Debug/urpg_tests.exe" "[presentation]")
  set_tests_properties([=[urpg_presentation_unit_lane]=] PROPERTIES  LABELS "pr;presentation" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;398;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_presentation_unit_lane]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/Release/urpg_tests.exe" "[presentation]")
  set_tests_properties([=[urpg_presentation_unit_lane]=] PROPERTIES  LABELS "pr;presentation" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;398;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_presentation_unit_lane]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/MinSizeRel/urpg_tests.exe" "[presentation]")
  set_tests_properties([=[urpg_presentation_unit_lane]=] PROPERTIES  LABELS "pr;presentation" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;398;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_presentation_unit_lane]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/RelWithDebInfo/urpg_tests.exe" "[presentation]")
  set_tests_properties([=[urpg_presentation_unit_lane]=] PROPERTIES  LABELS "pr;presentation" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;398;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_presentation_unit_lane]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[urpg_spatial_editor_lane]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/Debug/urpg_tests.exe" "[editor][spatial]")
  set_tests_properties([=[urpg_spatial_editor_lane]=] PROPERTIES  LABELS "pr;presentation;editor" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;407;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[urpg_spatial_editor_lane]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/Release/urpg_tests.exe" "[editor][spatial]")
  set_tests_properties([=[urpg_spatial_editor_lane]=] PROPERTIES  LABELS "pr;presentation;editor" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;407;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[urpg_spatial_editor_lane]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/MinSizeRel/urpg_tests.exe" "[editor][spatial]")
  set_tests_properties([=[urpg_spatial_editor_lane]=] PROPERTIES  LABELS "pr;presentation;editor" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;407;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[urpg_spatial_editor_lane]=] "C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/RelWithDebInfo/urpg_tests.exe" "[editor][spatial]")
  set_tests_properties([=[urpg_spatial_editor_lane]=] PROPERTIES  LABELS "pr;presentation;editor" _BACKTRACE_TRIPLES "C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;407;add_test;C:/Users/dferr/dev/URPG - RPG Game Maker/CMakeLists.txt;0;")
else()
  add_test([=[urpg_spatial_editor_lane]=] NOT_AVAILABLE)
endif()
subdirs("_deps/catch2-build")
subdirs("_deps/nlohmann_json-build")
subdirs("_deps/sdl2-build")
