if(NOT CTEST_CONFIGURATION_TYPE)
  message("No configuration for testing specified, use '-C <cfg>'.")
else()
  include("C:/Users/dferr/dev/URPG - RPG Game Maker/build-local/urpg_snapshot_tests-b12d07c_include-${CTEST_CONFIGURATION_TYPE}.cmake")
endif()
