if(NOT CTEST_CONFIGURATION_TYPE)
  message("No configuration for testing specified, use '-C <cfg>'.")
else()
  include("C:/dev/URPG Maker/build-local/urpg_integration_tests-b12d07c_include-${CTEST_CONFIGURATION_TYPE}.cmake")
endif()
