#include "engine/core/events/event_reference_picker.h"
#include <algorithm>
#include <array>
#include <cctype>
#include <tuple>

namespace urpg::events {
const char* eventReferenceKindId(EventReferenceKind kind){switch(kind){case EventReferenceKind::Map:return"map";case EventReferenceKind::MapEntry:return"map_entry";case EventReferenceKind::Event:return"event";case EventReferenceKind::Actor:return"actor";case EventReferenceKind::Item:return"item";case EventReferenceKind::Skill:return"skill";case EventReferenceKind::Switch:return"switch";case EventReferenceKind::Variable:return"variable";case EventReferenceKind::CommonEvent:return"common_event";case EventReferenceKind::Audio:return"audio";case EventReferenceKind::Animation:return"animation";case EventReferenceKind::Quest:return"quest";case EventReferenceKind::Dialogue:return"dialogue";}return"map";}
std::optional<EventReferenceKind> pickerKindForEventCommand(EventCommandKind kind){switch(kind){case EventCommandKind::Transfer:return EventReferenceKind::MapEntry;case EventCommandKind::MovementRoute:case EventCommandKind::Camera:return EventReferenceKind::Event;case EventCommandKind::Item:return EventReferenceKind::Item;case EventCommandKind::Switch:return EventReferenceKind::Switch;case EventCommandKind::Variable:return EventReferenceKind::Variable;case EventCommandKind::CommonEvent:return EventReferenceKind::CommonEvent;case EventCommandKind::Sound:return EventReferenceKind::Audio;case EventCommandKind::Animation:return EventReferenceKind::Animation;default:return std::nullopt;}}
bool EventReferencePickerCatalog::add(EventReferenceOption option){if(option.stable_id.empty()||option.label.empty()||std::any_of(options_.begin(),options_.end(),[&](const auto& existing){return existing.kind==option.kind&&existing.stable_id==option.stable_id;}))return false;options_.push_back(std::move(option));return true;}
std::vector<EventReferenceOption> EventReferencePickerCatalog::search(EventReferenceKind kind,std::string query)const{std::transform(query.begin(),query.end(),query.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});std::vector<EventReferenceOption> result;for(const auto& option:options_){if(option.kind!=kind)continue;auto text=option.label+" "+option.stable_id+" "+option.detail;std::transform(text.begin(),text.end(),text.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});if(query.empty()||text.find(query)!=std::string::npos)result.push_back(option);}std::sort(result.begin(),result.end(),[](const auto& a,const auto& b){if(a.available!=b.available)return a.available;return std::tie(a.label,a.stable_id)<std::tie(b.label,b.stable_id);});return result;}
std::optional<EventReferenceOption> EventReferencePickerCatalog::resolve(EventReferenceKind kind,const std::string& id)const{const auto found=std::find_if(options_.begin(),options_.end(),[&](const auto& option){return option.kind==kind&&option.stable_id==id;});return found==options_.end()?std::nullopt:std::optional<EventReferenceOption>(*found);}
EventReferenceBindingResult EventReferencePickerCatalog::bind(EventCommand command,EventReferenceKind kind,const std::string& id)const{const auto option=resolve(kind,id);if(!option)return {false,"event_reference_missing",std::move(command)};if(!option->available)return {false,"event_reference_unavailable",std::move(command)};command.target=option->stable_id;command.payload["reference"]={{"kind",eventReferenceKindId(kind)},{"stable_id",option->stable_id},{"label",option->label},{"owner_id",option->owner_id}};return {true,"event_reference_bound",std::move(command)};}
std::vector<EventReferenceKind> EventReferencePickerCatalog::supportedKinds()const{return {EventReferenceKind::Map,EventReferenceKind::MapEntry,EventReferenceKind::Event,EventReferenceKind::Actor,EventReferenceKind::Item,EventReferenceKind::Skill,EventReferenceKind::Switch,EventReferenceKind::Variable,EventReferenceKind::CommonEvent,EventReferenceKind::Audio,EventReferenceKind::Animation,EventReferenceKind::Quest,EventReferenceKind::Dialogue};}
} // namespace urpg::events
