#pragma once

#include <string>
#include <vector>
#include <cstdint>
#include <algorithm>

#include <nlohmann/json.hpp>

namespace urpg::tools {

/**
 * @brief Metadata for a single sprite within an atlas.
 */
struct SpriteRect {
    std::string id;
    int32_t x, y, width, height;
    int32_t pivotX, pivotY;
};

struct SpriteAnimationClip {
    std::string id;
    std::vector<std::string> frames;
    float frameDuration = 0.15f;
    bool loop = true;
};

struct SpriteAtlasPreview {
    std::string defaultAnimation;
    int32_t frameCount = 0;
    std::vector<std::string> orderedSpriteIds;
};

/**
 * @brief Definition of a sprite atlas generated by the pipeline.
 */
struct SpriteAtlas {
    std::string atlasName;
    std::string texturePath;
    int32_t width, height;
    std::vector<SpriteRect> sprites;
    std::vector<SpriteAnimationClip> animations;
    SpriteAtlasPreview preview;
};

inline void populatePreviewArtifacts(SpriteAtlas& atlas) {
    atlas.preview.orderedSpriteIds.clear();
    atlas.preview.frameCount = 0;
    atlas.preview.defaultAnimation.clear();

    if (atlas.sprites.empty()) {
        atlas.animations.clear();
        return;
    }

    for (const auto& sprite : atlas.sprites) {
        atlas.preview.orderedSpriteIds.push_back(sprite.id);
    }
    std::sort(atlas.preview.orderedSpriteIds.begin(), atlas.preview.orderedSpriteIds.end());

    SpriteAnimationClip clip;
    clip.id = "preview_loop";
    clip.frames = atlas.preview.orderedSpriteIds;

    atlas.animations.clear();
    atlas.animations.push_back(clip);
    atlas.preview.defaultAnimation = clip.id;
    atlas.preview.frameCount = static_cast<int32_t>(clip.frames.size());
}

inline nlohmann::json toJson(const SpriteAtlas& atlas) {
    nlohmann::json j;
    j["atlasName"] = atlas.atlasName;
    j["texturePath"] = atlas.texturePath;
    j["size"] = { atlas.width, atlas.height };

    nlohmann::json spritesJson = nlohmann::json::array();
    for (const auto& sprite : atlas.sprites) {
        spritesJson.push_back({
            {"id", sprite.id},
            {"x", sprite.x},
            {"y", sprite.y},
            {"w", sprite.width},
            {"h", sprite.height},
            {"pivot", {sprite.pivotX, sprite.pivotY}}
        });
    }
    j["sprites"] = spritesJson;

    nlohmann::json animationsJson = nlohmann::json::array();
    for (const auto& animation : atlas.animations) {
        animationsJson.push_back({
            {"id", animation.id},
            {"frames", animation.frames},
            {"frameDuration", animation.frameDuration},
            {"loop", animation.loop}
        });
    }
    j["animations"] = animationsJson;
    j["preview"] = {
        {"defaultAnimation", atlas.preview.defaultAnimation},
        {"frameCount", atlas.preview.frameCount},
        {"orderedSpriteIds", atlas.preview.orderedSpriteIds}
    };
    return j;
}

} // namespace urpg::tools
