#pragma once

#include <string>
#include <vector>
#include <cstdint>

namespace urpg::tools {

/**
 * @brief Metadata for a single sprite within an atlas.
 */
struct SpriteRect {
    std::string id;
    int32_t x, y, width, height;
    int32_t pivotX, pivotY;
};

/**
 * @brief Definition of a sprite atlas generated by the pipeline.
 */
struct SpriteAtlas {
    std::string atlasName;
    std::string texturePath;
    int32_t width, height;
    std::vector<SpriteRect> sprites;
};

} // namespace urpg::tools
