#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
from pathlib import Path

SAFE_REMOVE_PREFIXES = ("itch/unzipped/",)
SAFE_KEEP_PREFIXES = (
    "third_party/itch-assets/packs/",
    "third_party/itch-assets/loose-files/",
    "third_party/rpgmaker-mz/",
    "third_party/huggingface/",
    "imports/root-drop/archives/",
)


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Safely prune duplicate files by using asset_hygiene duplicate report. "
            "Only removes files in itch/unzipped when canonical copies exist in approved roots."
        )
    )
    p.add_argument("--repo-root", default=".", help="Repository root")
    p.add_argument(
        "--duplicates-csv",
        default="imports/reports/asset_hygiene_duplicates.csv",
        help="CSV generated by asset_hygiene.py",
    )
    p.add_argument("--plan-csv", default="imports/reports/asset_safe_dedupe_plan.csv")
    p.add_argument("--applied-csv", default="imports/reports/asset_safe_dedupe_applied.csv")
    p.add_argument("--summary-json", default="imports/reports/asset_safe_dedupe_summary.json")
    p.add_argument("--apply", action="store_true", help="Apply deletions. Default is plan-only.")
    p.add_argument(
        "--max-removals",
        type=int,
        default=0,
        help="Optional cap on removals when --apply is used (0 means no cap).",
    )
    return p.parse_args()


def is_safe_remove(path_rel: str) -> bool:
    return any(path_rel.startswith(prefix) for prefix in SAFE_REMOVE_PREFIXES)


def is_safe_keep(path_rel: str) -> bool:
    return any(path_rel.startswith(prefix) for prefix in SAFE_KEEP_PREFIXES)


def prune_empty_dirs(start_file: Path, stop_dir: Path) -> list[str]:
    removed: list[str] = []
    cur = start_file.parent
    while True:
        if cur == stop_dir or stop_dir not in cur.parents and cur != stop_dir:
            break
        if not cur.exists() or not cur.is_dir():
            break
        try:
            next(cur.iterdir())
            break
        except StopIteration:
            cur.rmdir()
            removed.append(str(cur))
            cur = cur.parent
        except OSError:
            break
    return removed


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    duplicates_csv = (repo_root / args.duplicates_csv).resolve()
    plan_csv = (repo_root / args.plan_csv).resolve()
    applied_csv = (repo_root / args.applied_csv).resolve()
    summary_json = (repo_root / args.summary_json).resolve()
    report_dir = plan_csv.parent
    report_dir.mkdir(parents=True, exist_ok=True)

    if not duplicates_csv.exists():
        raise SystemExit(f"Missing duplicates CSV: {duplicates_csv}")

    plan_rows: list[dict[str, str]] = []
    applied_rows: list[dict[str, str]] = []

    with duplicates_csv.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            path_rel = row.get("path_rel", "")
            keep_rel = row.get("recommended_keep", "")
            remove_flag = row.get("recommended_remove", "").lower() == "yes"
            if not remove_flag:
                continue
            if not is_safe_remove(path_rel):
                continue
            if not is_safe_keep(keep_rel):
                continue
            plan_rows.append(
                {
                    "path_rel": path_rel,
                    "recommended_keep": keep_rel,
                    "sha256": row.get("sha256", ""),
                    "size_bytes": row.get("size_bytes", ""),
                    "eligible_reason": "itch_unzipped_duplicate_with_safe_canonical_copy",
                }
            )

    plan_rows.sort(key=lambda r: r["path_rel"])

    with plan_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["path_rel", "recommended_keep", "sha256", "size_bytes", "eligible_reason"],
        )
        writer.writeheader()
        writer.writerows(plan_rows)

    removed_count = 0
    missing_count = 0
    skipped_by_cap = 0
    removed_bytes = 0
    removed_empty_dirs = 0

    if args.apply:
        cap = args.max_removals if args.max_removals > 0 else None
        stop_dir = (repo_root / "itch" / "unzipped").resolve()
        for row in plan_rows:
            if cap is not None and removed_count >= cap:
                skipped_by_cap += 1
                continue

            target = (repo_root / row["path_rel"]).resolve()
            keep = (repo_root / row["recommended_keep"]).resolve()
            if not target.exists():
                missing_count += 1
                continue
            if not keep.exists():
                continue
            if not target.is_file():
                continue
            size = target.stat().st_size
            target.unlink()
            removed_count += 1
            removed_bytes += size
            removed_dirs = prune_empty_dirs(target, stop_dir)
            removed_empty_dirs += len(removed_dirs)
            applied_rows.append(
                {
                    "path_rel": row["path_rel"],
                    "recommended_keep": row["recommended_keep"],
                    "sha256": row["sha256"],
                    "size_bytes": str(size),
                    "applied_at": now_iso(),
                }
            )

    with applied_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["path_rel", "recommended_keep", "sha256", "size_bytes", "applied_at"],
        )
        writer.writeheader()
        writer.writerows(applied_rows)

    summary = {
        "generated_at": now_iso(),
        "repo_root": str(repo_root),
        "duplicates_csv": str(duplicates_csv),
        "plan_count": len(plan_rows),
        "apply_mode": bool(args.apply),
        "max_removals": args.max_removals,
        "removed_count": removed_count,
        "removed_bytes": removed_bytes,
        "missing_count": missing_count,
        "skipped_by_cap": skipped_by_cap,
        "removed_empty_dirs": removed_empty_dirs,
        "plan_csv": str(plan_csv),
        "applied_csv": str(applied_csv),
    }
    summary_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(f"PLAN_COUNT\t{len(plan_rows)}")
    print(f"APPLY_MODE\t{args.apply}")
    print(f"REMOVED_COUNT\t{removed_count}")
    print(f"REMOVED_BYTES\t{removed_bytes}")
    print(f"MISSING_COUNT\t{missing_count}")
    print(f"SKIPPED_BY_CAP\t{skipped_by_cap}")
    print(f"REMOVED_EMPTY_DIRS\t{removed_empty_dirs}")
    print(f"PLAN_CSV\t{plan_csv}")
    print(f"APPLIED_CSV\t{applied_csv}")
    print(f"SUMMARY_JSON\t{summary_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
