#include "engine/core/editor/editor_panel_registry.h"

#include <algorithm>

namespace urpg::editor {

namespace {

const std::vector<EditorPanelRegistryEntry> kRegistry = {
    {"diagnostics", "Diagnostics", "System", EditorPanelExposure::ReleaseTopLevel, "editor/diagnostics",
     "Top-level diagnostics workspace and nested validation panels."},
    {"assets", "Assets", "Content", EditorPanelExposure::ReleaseTopLevel, "editor/assets",
     "Top-level asset library and hygiene surface."},
    {"ability", "Ability Inspector", "Gameplay", EditorPanelExposure::ReleaseTopLevel, "editor/ability",
     "Top-level ability runtime and authoring inspector."},
    {"patterns", "Pattern Field Editor", "Gameplay", EditorPanelExposure::ReleaseTopLevel, "editor/ability",
     "Top-level pattern authoring surface required by editor smoke."},
    {"status_effect_designer", "Status Effect Designer", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Buff/debuff authoring, live preview, runtime effect execution, diagnostics, and saved project data."},
    {"enemy_ai_behavior_tree", "Enemy AI Behavior Tree", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Enemy AI condition/priority authoring, live action preview, runtime execution, diagnostics, and saved project data."},
    {"boss_phase_script", "Boss Phase Script", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Boss phase threshold authoring, live phase preview, runtime execution, diagnostics, and saved project data."},
    {"equipment_set_bonus", "Equipment Set Bonus", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Equipment set threshold authoring, stat/effect preview, runtime grants, diagnostics, and saved project data."},
    {"dungeon_room_flow", "Dungeon Room Flow", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Dungeon room graph authoring, lock/key preview, runtime edge unlocks, diagnostics, and saved project data."},
    {"companion_banter", "Companion Banter", "Narrative", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Party banter context authoring, localization preview, runtime line execution, diagnostics, and saved project data."},
    {"quest_choice_consequence", "Quest Choice Consequence", "Narrative", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Quest choice outcome authoring, consequence preview, runtime variable/reward writes, diagnostics, and saved project data."},
    {"shop_economy_sim_lab", "Shop Economy Sim Lab", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Shop stock and pricing authoring, economy preview, runtime deltas, diagnostics, and saved project data."},
    {"puzzle_mechanic_builder", "Puzzle Mechanic Builder", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Puzzle rule authoring, switch/timer preview, runtime state changes, diagnostics, and saved project data."},
    {"world_state_timeline", "World State Timeline", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Calendar/world event authoring, timeline preview, runtime world-state writes, diagnostics, and saved project data."},
    {"tactical_terrain_effects", "Tactical Terrain Effects", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Terrain effect authoring, movement/hazard preview, runtime tactical deltas, diagnostics, and saved project data."},
    {"procedural_content_rules", "Procedural Content Rules", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/gameplay", "Procedural rule authoring, seed/rule preview, runtime generation modifiers, diagnostics, and saved project data."},
    {"smart_event_workflow", "Smart Event Workflow", "Events", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "Smart chest, smart door, and event default authoring with live runtime command preview."},
    {"event_template_library", "Event Template Library", "Events", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "Searchable event template library with categories, dependency preview, and clipboard execution."},
    {"interaction_prompt_system", "Interaction Prompt System", "Events", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "On-map Open/Read/Talk/Inspect/Enter prompt authoring with live visibility preview."},
    {"message_log_history", "Message Log History", "Narrative", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "Dialogue history capture, speaker/face/choice logging, menu access, diagnostics, and saved project data."},
    {"minimap_fog_of_war", "Minimap and Fog of War", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "Minimap, POI, zoom, map-name, and persistent fog-of-war authoring with runtime preview."},
    {"picture_hotspot_common_event", "Picture Hotspot Common Event", "Events", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "Clickable picture hotspot authoring with common-event binding, hover preview, and hit-test rules."},
    {"common_event_menu_builder", "Common Event Menu Builder", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "Common-event menu layout authoring with help/picture/subtext windows and switch visibility."},
    {"developer_debug_overlay", "Developer Debug Overlay", "Diagnostics", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "Dev-only console, quick reload, battle test, map transfer, save, and region overlay controls."},
    {"switch_variable_inspector", "Switch Variable Inspector", "Diagnostics", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "Switch/variable graph, usage search, rename/refactor, unused scan, and condition simplification preview."},
    {"asset_dlc_library_manager", "Asset DLC Library Manager", "Content", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "Global asset pack mounting, import-on-demand, collision diagnostics, and export inclusion preview."},
    {"hud_maker", "HUD Maker", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "Map and battle HUD authoring with widget preview and accessibility labels."},
    {"plugin_conflict_resolver", "Plugin Conflict Resolver", "Runtime", EditorPanelExposure::ReleaseTopLevel,
     "editor/community", "Plugin dependency, load-order, incompatibility, native replacement, and patch suggestion analysis."},
    {"project_search_everywhere", "Project Search Everywhere", "Project", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Cross-project search across maps, events, assets, variables, switches, dialogue, quests, plugins, and scripts."},
    {"broken_reference_repair", "Broken Reference Repair", "Project", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Missing asset, database, map, event, and localization reference repair with live retarget preview."},
    {"mass_edit_batch_operations", "Mass Edit and Batch Operations", "Project", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Bulk event, tile, database, and metadata editing with before/after preview and runtime-safe operations."},
    {"project_diff_change_review", "Project Diff and Change Review", "Project", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Project snapshot comparison, changed-resource review, and export-risk preview."},
    {"template_instance_sync", "Template Instance Sync", "Project", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Template-to-instance sync preview with local override protection and runtime data updates."},
    {"parallax_mapping_editor", "Parallax Mapping Editor", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Layered parallax authoring with live map preview, passability overlay, and saved runtime layer data."},
    {"collision_passability_visualizer", "Collision Passability Visualizer", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Tile, region, event, vehicle, and ladder/bush/counter passability overlays with runtime collision preview."},
    {"world_map_route_planner", "World Map Route Planner", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Overworld route graph authoring with path, unlock, encounter, and travel-cost preview."},
    {"secret_hidden_object_authoring", "Secret Hidden Object Authoring", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Hidden passages, inspectables, sparkle rules, switches, and reveal behavior authoring with live preview."},
    {"biome_rule_system", "Biome Rule System", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Region biome rules for encounters, weather, palette, audio, gathering, and movement modifiers."},
    {"dialogue_relationship_matrix", "Dialogue Relationship Matrix", "Narrative", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Relationship-aware dialogue matrix authoring with portrait, variable, affinity, and localization preview."},
    {"branch_coverage_preview", "Branch Coverage Preview", "Narrative", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Dialogue and quest branch reachability analysis with unreachable-choice diagnostics."},
    {"cutscene_blocking_tool", "Cutscene Blocking Tool", "Presentation", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Actor mark, camera, facing, timing, and collision blocking preview for cutscene authoring."},
    {"localization_context_review", "Localization Context Review", "Content", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "String context review with screenshots, speaker, gender/plural notes, variables, and in-scene preview."},
    {"damage_formula_visual_lab", "Damage Formula Visual Lab", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Damage formula graphing, sample battler matrices, variance, guard, element, and state preview."},
    {"enemy_troop_timeline_preview", "Enemy Troop Timeline Preview", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Troop turn, cooldown, AI action, summon, phase, and event-page timeline preview."},
    {"skill_combo_chain_builder", "Skill Combo Chain Builder", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Skill chain, tag, opener, finisher, resource, and cooldown authoring with runtime combo execution."},
    {"bestiary_discovery_system", "Bestiary Discovery System", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Enemy discovery, drops, hints, scan rules, weaknesses, and completion tracking authoring."},
    {"formation_positioning_system", "Formation Positioning System", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Party/troop slot, row, threat, range, and formation bonus preview with saved runtime data."},
    {"menu_builder", "Menu Builder", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Main, pause, battle, shop, and custom menu composition with exact runtime preview."},
    {"journal_hub", "Journal Hub", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Quest, codex, bestiary, tutorial, lore, and discovered clue journal authoring with runtime preview."},
    {"notification_toast_system", "Notification and Toast System", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Quest, loot, discovery, achievement, warning, and hint toast authoring with live timing preview."},
    {"input_prompt_skinner", "Input Prompt Skinner", "Input", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Keyboard, controller, touch, and remap-aware prompt skinning with runtime glyph preview."},
    {"playtest_session_recorder", "Playtest Session Recorder", "Diagnostics", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Playtest input, seed, map, save, branch, and performance trace recording for replayable reports."},
    {"bug_report_packager", "Bug Report Packager", "Diagnostics", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Save, trace, logs, screenshots, project diff, and environment bundle creation for bug reports."},
    {"performance_heatmap", "Performance Heatmap", "Diagnostics", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Map, event, rendering, script, audio, and asset hot-spot visualization with runtime frame data."},
    {"release_checklist_dashboard", "Release Checklist Dashboard", "Release", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Release gates for export, legal, accessibility, localization, compatibility, saves, and store readiness."},
    {"store_page_asset_generator", "Store Page Asset Generator", "Release", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Capsule, screenshot, trailer still, icon, banner, and storefront metadata asset generation preview."},
    {"mod_conflict_visualizer", "Mod Conflict Visualizer", "Runtime", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Mod load-order, file override, database row, script hook, and dependency conflict visualization."},
    {"mod_packaging_wizard", "Mod Packaging Wizard", "Runtime", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Mod manifest, dependency, asset inclusion, compatibility, signing, and publish package authoring."},
    {"plugin_to_native_migration_advisor", "Plugin-to-Native Migration Advisor", "Runtime", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Plugin API usage analysis, native replacement mapping, risk review, and migration task generation."},
    {"fast_travel_system", "Fast Travel System", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Destination unlocks, costs, route preview, save-state visibility, and runtime warp execution."},
    {"platformer_game_type", "Platformer Game Type", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Side-view map, camera, controller, and collision authoring for platformer-style game templates."},
    {"gacha_system", "Gacha System", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Pool, rarity, pity, duplicate, currency, and summon result authoring with probability preview."},
    {"map_zoom_system", "Map Zoom System", "Presentation", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Runtime map zoom, camera anchoring, smoothing, pixel snapping, and cutscene zoom preview."},
    {"pictures_ui_creator", "Picture-Based UI Creator", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Drag-and-drop picture UI canvas with text boxes, attachments, animations, navigation, and saved layout data."},
    {"realtime_event_effects_builder", "Realtime Event Effects Builder", "Presentation", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Live event/player/follower sprite effects with transform, hue, opacity, blend, and animation presets."},
    {"directional_shadow_system", "Directional Shadow System", "Rendering", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Fake sun angle, player/event/battle shadow casting, group tags, length, opacity, blur, skew, and z-index preview."},
    {"dynamic_environment_effects_builder", "Dynamic Environment Effects Builder", "Rendering", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Layered fog, leaves, light rays, particle presets, depth, texture, and map/battle environment preview."},
    {"camera_director", "Camera Director", "Presentation", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Camera rails, pans, focus targets, shake, zoom cues, smoothing, and cutscene camera preview."},
    {"screen_filter_post_fx_builder", "Screen Filter and Post FX Builder", "Rendering", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Tint, bloom, blur, vignette, CRT, pixelation, color grading, and masked runtime screen effects."},
    {"weather_composer", "Weather Composer", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Rain, snow, ash, sandstorm, lightning, puddle, wet-surface, indoor-mask, and audio weather preview."},
    {"lighting_painter", "Lighting Painter", "Rendering", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Point lights, cone lights, flicker, torches, day/night curves, and region light blocker authoring."},
    {"platformer_physics_lab", "Platformer Physics Lab", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Gravity, jump arcs, coyote time, wall jump, slopes, ladders, hazards, and moving-platform simulation."},
    {"side_view_action_combat_kit", "Side-View Action Combat Kit", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Hitboxes, hurtboxes, combo windows, knockback, invulnerability frames, patrols, and attack previews."},
    {"summon_gacha_banner_builder", "Summon Gacha Banner Builder", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Banner art, featured pools, rate disclosure, pity, duplicate conversion, and ten-pull preview."},
    {"fast_travel_map_builder", "Fast Travel Map Builder", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "World-node route map authoring with unlock badges, route lines, costs, and runtime save-state preview."},
    {"quest_board_mission_builder", "Quest Board and Mission Builder", "Narrative", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Mission postings, rewards, timers, prerequisites, repeatable jobs, and quest-board preview."},
    {"relationship_event_scheduler", "Relationship Event Scheduler", "Narrative", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Affinity gates, gifts, daily and seasonal relationship events, conflicts, and runtime schedule preview."},
    {"farming_garden_plot_builder", "Farming and Garden Plot Builder", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Crop plots, growth stages, watering, soil, seasons, pests, and harvest yield preview."},
    {"fishing_minigame_builder", "Fishing Minigame Builder", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Fish tables, bait, timing windows, rarity, weather, region rules, and catch preview."},
    {"mount_vehicle_system", "Mount and Vehicle System", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Mounts, boats, airships, speed, terrain permissions, mounting animations, and navigation preview."},
    {"stealth_system", "Stealth System", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Vision cones, noise radius, hiding spots, patrol routes, alert states, and stealth simulation."},
    {"puzzle_logic_board", "Puzzle Logic Board", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Pressure plates, switches, blocks, lasers, mirrors, gates, reset rules, and solution preview."},
    {"in_game_phone_messenger", "In-Game Phone and Messenger UI", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Contacts, text threads, calls, notifications, story triggers, and runtime phone preview."},
    {"crafting_recipe_graph", "Crafting Recipe Graph", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Recipe dependency graphs, stations, ingredients, unlocks, and economy impact preview."},
    {"housing_decoration_editor", "Housing and Decoration Editor", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Furniture placement, rotation, grid snapping, collision, room themes, and housing runtime preview."},
    {"companion_command_wheel", "Companion Command Wheel", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Party command radial menus, tactics, formations, contextual actions, and runtime input preview."},
    {"title_save_screen_builder", "Title and Save Screen Builder", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Title, pause, save slot, animated button, background, and save-card screen authoring."},
    {"credits_ending_builder", "Credits and Ending Builder", "Presentation", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Credit rolls, ending unlocks, screenshots, music cues, scroll timing, and ending preview."},
    {"tutorial_overlay_builder", "Tutorial Overlay Builder", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Callouts, arrows, highlight regions, input prompts, and tutorial progression gate preview."},
    {"accessibility_preview_lab", "Accessibility Preview Lab", "Quality", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Font scaling, contrast, colorblind filters, subtitles, remap preview, and accessibility profile simulation."},
    {"economy_balance_simulator", "Economy Balance Simulator", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Gold faucets/sinks, shop prices, drop rates, inflation warnings, and long-run economy simulation."},
    {"enemy_encounter_zone_painter", "Enemy Encounter Zone Painter", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Encounter zone painting, enemy weights, level scaling, region rules, and encounter heatmap preview."},
    {"random_dungeon_room_stitcher", "Random Dungeon Room Stitcher", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Room pools, door connectors, lock/key graphs, treasure budgets, seeds, and generated layout preview."},
    {"achievement_visual_builder", "Achievement Visual Builder", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Achievement cards, unlock conditions, hidden states, toast preview, and platform-neutral export payloads."},
    {"mod_marketplace_packager", "Mod Marketplace Packager", "Runtime", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Marketplace listing, screenshots, manifests, permissions, dependencies, and compatibility scan preview."},
    {"proximity_compass_objective_radar", "Proximity Compass and Objective Radar", "UI",
     EditorPanelExposure::ReleaseTopLevel, "editor/maker",
     "Objective radar, nearby-event compass, distance labels, quest marker filtering, and runtime HUD preview."},
    {"resource_manager_unused_asset_cleaner", "Resource Manager and Unused Asset Cleaner", "Content",
     EditorPanelExposure::ReleaseTopLevel, "editor/maker",
     "Unused file discovery, reference tracing, safe delete preview, duplicate grouping, and repair workflow."},
    {"visual_inventory_builder", "Visual Inventory Builder", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Inventory grid/list layout, item cards, categories, comparison panels, and runtime inventory preview."},
    {"animated_pictures_timeline", "Animated Pictures Timeline", "Presentation", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Picture keyframes, easing curves, loops, tween tracks, and Show Picture runtime animation preview."},
    {"horror_fx_builder", "Horror FX Builder", "Presentation", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Jumpscare cues, distortion, flicker, camera pulses, chase overlays, and audio stinger preview."},
    {"cutscene_skip_fast_forward", "Cutscene Skip and Fast Forward", "Presentation",
     EditorPanelExposure::ReleaseTopLevel, "editor/maker",
     "Skip and fast-forward rules, hold-to-skip, recap cards, choice safeguards, and runtime cutscene preview."},
    {"translation_helper_workspace", "Translation Helper Workspace", "Localization", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "String extraction, import/export, missing translation review, context checks, and runtime text preview."},
    {"deployment_cook_dashboard", "Deployment Cook Dashboard", "Release", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Creator-facing cook workflow for package targets, compression, signing preview, and release checks."},
    {"break_shield_system", "Break Shield System", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Enemy shield bars, weakness damage, break states, stun windows, and battle preview."},
    {"boost_point_system", "Boost Point System", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Turn-resource banking, boost spending, command amplification, limits, and battle simulation."},
    {"battle_weapon_swap", "Battle Weapon Swap", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Mid-battle weapon loadouts, swap costs, stat deltas, command UI, and runtime preview."},
    {"order_turn_battle_system", "Order Turn Battle System", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Visible turn queue, speed/delay rules, action inserts, reorder diagnostics, and battle timeline preview."},
    {"item_concoction_system", "Item Concoction System", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Battle item mixing, ingredient pairs, result tables, consumption rules, and effect preview."},
    {"unison_attack_builder", "Unison Attack Builder", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Dual/triple tech requirements, party resources, animation tracks, and battle result preview."},
    {"timed_attack_qte_builder", "Timed Attack and QTE Builder", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Timing windows, input sequences, success/fail branches, randomization, and battle trigger preview."},
    {"action_sequence_impact_builder", "Action Sequence Impact Builder", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Hit stop, camera shake, flashes, trails, zoom, impact timing, and skill action preview."},
    {"side_battle_status_ui_builder", "Side Battle Status UI Builder", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Side battle HUD layout, actor cards, gauges, portraits, states, and runtime battle UI preview."},
    {"victory_screen_builder", "Victory Screen Builder", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "EXP, loot, rank, level-up, unlocks, rewards, and victory summary screen preview."},
    {"state_tooltip_display", "State Tooltip Display", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Buff/debuff tooltip cards, turn counts, icon focus, accessibility labels, and battle preview."},
    {"animated_loading_screen_builder", "Animated Loading Screen Builder", "Presentation",
     EditorPanelExposure::ReleaseTopLevel, "editor/maker",
     "Loading animations, progress bindings, tips, transitions, and runtime loading screen preview."},
    {"popup_builder", "Popup Builder", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Loot, quest, warning, and custom popup styling with anchor, timing, and runtime preview."},
    {"animated_window_builder", "Animated Window Builder", "UI", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Windowskins, variable-driven styles, open/close animations, and runtime window preview."},
    {"video_player_surface", "Video Player Surface", "Presentation", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Video cutscenes, subtitle tracks, skip markers, audio sync, and runtime video preview."},
    {"tactical_battle_system", "Tactical Battle System", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "SRPG grid combat, movement ranges, terrain costs, objectives, and tactical battle preview."},
    {"bullet_hell_maker", "Bullet Hell Maker", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Projectile patterns, hitboxes, waves, boss phases, and bullet-hell runtime preview."},
    {"duelist_card_battle_system", "Duelist Card Battle System", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Decks, hand preview, card costs, draw/discard, enemy AI, and card battle simulation."},
    {"spin_top_battle_system", "Spin Top Battle System", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Arena setup, spin stats, collisions, stamina, knockouts, and toy-battle simulation."},
    {"recruiting_board", "Recruiting Board", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Actor hire/retire boards, costs, availability, contracts, and party preview."},
    {"step_rewards_system", "Step Rewards System", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Walking milestones, reward tables, exploration counters, reset rules, and runtime reward preview."},
    {"event_spawner_solution", "Event Spawner Solution", "Events", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Template-map event spawning, persistence, transfer events, spawn rules, and runtime preview."},
    {"smart_event_timers_progress", "Smart Event Timers and Progress", "Events", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Timed event states, progress bars, interrupt rules, completion branches, and runtime timer preview."},
    {"actor_construct", "Actor Construct", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Actor body, class, parts, stat allocation, portrait, and runtime construction preview."},
    {"equip_construct_visible_equipment", "Equip Construct and Visible Equipment", "Gameplay",
     EditorPanelExposure::ReleaseTopLevel, "editor/maker",
     "Visible equipment layers, paperdoll preview, stat deltas, sprite layers, and runtime equipment visuals."},
    {"skill_equip_system", "Skill Equip System", "Gameplay", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Limited skill slots, loadouts, passive/active rules, class restrictions, and battle command preview."},
    {"front_view_battler_mode", "Front View Battler Mode", "Battle", EditorPanelExposure::ReleaseTopLevel,
     "editor/maker", "Front-view battle layout, enemy stage rows, actor command UI, and runtime battle preview."},
    {"mod", "Mod Manager", "Runtime", EditorPanelExposure::ReleaseTopLevel, "editor/mod",
     "Top-level mod registry, loader, and validation surface."},
    {"analytics", "Analytics", "Runtime", EditorPanelExposure::ReleaseTopLevel, "editor/analytics",
     "Top-level telemetry privacy, validation, and upload surface."},

    {"compat_report", "Compatibility Report", "Diagnostics", EditorPanelExposure::Nested,
     "editor/diagnostics", "Rendered inside DiagnosticsWorkspace as the Compat tab."},
    {"save_inspector", "Save Inspector", "Diagnostics", EditorPanelExposure::Nested,
     "editor/diagnostics", "Rendered inside DiagnosticsWorkspace as the Save tab."},
    {"event_authority", "Event Authority", "Diagnostics", EditorPanelExposure::Nested,
     "editor/diagnostics", "Rendered inside DiagnosticsWorkspace as the Event Authority tab."},
    {"message_inspector", "Message Inspector", "Diagnostics", EditorPanelExposure::Nested,
     "editor/diagnostics", "Rendered inside DiagnosticsWorkspace as the Message Text tab."},
    {"battle_inspector", "Battle Inspector", "Diagnostics", EditorPanelExposure::Nested,
     "editor/diagnostics", "Rendered inside DiagnosticsWorkspace as the Battle tab."},
    {"menu_inspector", "Menu Inspector", "Diagnostics", EditorPanelExposure::Nested,
     "editor/diagnostics", "Rendered inside DiagnosticsWorkspace as the Menu tab."},
    {"menu_preview", "Menu Preview", "Diagnostics", EditorPanelExposure::Nested,
     "editor/diagnostics", "Rendered inside DiagnosticsWorkspace as the Menu preview surface."},
    {"audio_inspector", "Audio Inspector", "Diagnostics", EditorPanelExposure::Nested,
     "editor/diagnostics", "Rendered inside DiagnosticsWorkspace as the Audio tab."},
    {"migration_wizard", "Migration Wizard", "Diagnostics", EditorPanelExposure::Nested,
     "editor/diagnostics", "Rendered inside DiagnosticsWorkspace as the Migration Wizard tab."},
    {"project_audit", "Project Audit", "Diagnostics", EditorPanelExposure::Nested,
     "editor/diagnostics", "Rendered inside DiagnosticsWorkspace as the Project Audit tab."},
    {"project_health", "Project Health", "Diagnostics", EditorPanelExposure::Nested,
     "editor/diagnostics", "Rendered inside DiagnosticsWorkspace as the Project Health tab."},

    {"diagnostics_bundle", "Diagnostics Bundle", "Diagnostics", EditorPanelExposure::DevOnly,
     "editor/diagnostics", "Dev-only diagnostics export tooling for support bundles; excluded from release navigation."},
    {"event_authoring", "Event Authoring", "Gameplay", EditorPanelExposure::Deferred, "editor/events",
     "Deferred until the event authoring workflow is selected for release shell registration."},
    {"plugin_inspector", "Plugin Inspector", "Runtime", EditorPanelExposure::Deferred, "editor/plugin",
     "Deferred until plugin compatibility triage is selected for release shell registration."},
    {"new_project_wizard", "New Project Wizard", "Project", EditorPanelExposure::Deferred, "editor/project",
     "Project creation wizard is invoked by project flow, not persistent top-level navigation."},
    {"quest", "Quest", "Narrative", EditorPanelExposure::ReleaseTopLevel, "editor/quest",
     "Quest objective graph authoring, live preview, runtime application, diagnostics, and project-data saving."},
    {"skill_tree", "Skill Tree", "Gameplay", EditorPanelExposure::ReleaseTopLevel, "editor/progression",
     "Skill tree/class progression authoring, unlock preview, runtime ability grants, diagnostics, and project-data saving."},
    {"dialogue_graph", "Dialogue Graph", "Narrative", EditorPanelExposure::Deferred, "editor/dialogue",
     "Deferred roadmap panel; dialogue graph editing is outside the current release shell."},
    {"narrative_continuity", "Narrative Continuity", "Narrative", EditorPanelExposure::Deferred,
     "editor/narrative", "Deferred roadmap panel; continuity authoring is outside the current release shell."},
    {"relationship", "Relationship", "Narrative", EditorPanelExposure::ReleaseTopLevel, "editor/relationship",
     "Relationship affinity authoring, event preview, runtime affinity application, diagnostics, and project-data saving."},
    {"localization_workspace", "Localization Workspace", "Content", EditorPanelExposure::Deferred,
     "editor/localization", "Deferred until localization import/export ownership is selected for release shell registration."},
    {"timeline", "Timeline", "Presentation", EditorPanelExposure::ReleaseTopLevel, "editor/timeline",
     "Timeline authoring and runtime playback preview surface."},
    {"cutscene_timeline", "Cutscene Timeline", "Presentation", EditorPanelExposure::ReleaseTopLevel, "editor/timeline",
     "Cutscene track authoring, localized cue preview, runtime timeline playback, diagnostics, and project-data saving."},
    {"replay", "Replay", "Presentation", EditorPanelExposure::Deferred, "editor/replay",
     "Deferred until replay review is selected for release shell registration."},
    {"capture", "Capture", "Presentation", EditorPanelExposure::Deferred, "editor/capture",
     "Deferred until capture tooling is selected for release shell registration."},
    {"photo_mode", "Photo Mode", "Presentation", EditorPanelExposure::Deferred, "editor/presentation",
     "Deferred until presentation photo tooling is selected for release shell registration."},
    {"database", "Database", "Content", EditorPanelExposure::Deferred, "editor/database",
     "Deferred until database editing ownership is selected for release shell registration."},
    {"balance", "Balance", "Gameplay", EditorPanelExposure::ReleaseTopLevel, "editor/balance",
     "Balance editing and simulation surface."},
    {"encounter_designer", "Encounter Designer", "Gameplay", EditorPanelExposure::ReleaseTopLevel, "editor/balance",
     "Encounter region/pool authoring, seeded preview, runtime table export, diagnostics, and project-data saving."},
    {"loot_generator", "Loot Generator", "Gameplay", EditorPanelExposure::ReleaseTopLevel, "editor/items",
     "Loot table and affix authoring, deterministic generated-item preview, diagnostics, and project-data saving."},
    {"vendor", "Vendor", "Gameplay", EditorPanelExposure::Deferred, "editor/shop",
     "Deferred until shop/vendor authoring is selected for release shell registration."},
    {"world", "World", "Worldbuilding", EditorPanelExposure::Deferred, "editor/world",
     "Deferred roadmap panel; worldbuilding workflow is outside the current release shell."},
    {"crafting", "Crafting", "Gameplay", EditorPanelExposure::ReleaseTopLevel, "editor/crafting",
     "Crafting/gathering/economy authoring, live loop preview, runtime application, diagnostics, and project-data saving."},
    {"codex", "Codex", "Content", EditorPanelExposure::Deferred, "editor/codex",
     "Deferred roadmap panel; codex authoring is outside the current release shell."},
    {"calendar", "Calendar", "Worldbuilding", EditorPanelExposure::Deferred, "editor/time",
     "Deferred roadmap panel; calendar authoring is outside the current release shell."},
    {"monster_collection", "Monster Collection", "Gameplay", EditorPanelExposure::ReleaseTopLevel, "editor/monster",
     "Monster capture, party/storage, evolution authoring, deterministic preview, diagnostics, and project-data saving."},
    {"npc", "NPC", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel, "editor/npc",
     "NPC schedule/daily routine authoring, time preview, runtime resolution, diagnostics, and project-data saving."},
    {"metroidvania_gates", "Metroidvania Gates", "Worldbuilding", EditorPanelExposure::ReleaseTopLevel,
     "editor/metroidvania", "Ability-gated region authoring, reachability preview, diagnostics, and project-data saving."},
    {"puzzle", "Puzzle", "Gameplay", EditorPanelExposure::Deferred, "editor/puzzle",
     "Deferred roadmap panel; puzzle authoring is outside the current release shell."},
    {"export_diagnostics", "Export Diagnostics", "Release", EditorPanelExposure::Deferred, "editor/export",
     "Deferred until export diagnostics are promoted from validation tooling into release navigation."},
    {"character_creator", "Character Creator", "Gameplay", EditorPanelExposure::Deferred, "editor/character",
     "Deferred until character creation workflow is selected for release shell registration."},
    {"achievement", "Achievement", "Gameplay", EditorPanelExposure::Deferred, "editor/achievement",
     "Deferred until achievement authoring is selected for release shell registration."},
    {"controller_binding", "Controller Binding", "Input", EditorPanelExposure::Deferred, "editor/action",
     "Deferred until controller binding UX is selected for release shell registration."},
    {"save_debugger", "Save Debugger", "Diagnostics", EditorPanelExposure::Deferred, "editor/save",
     "Deferred diagnostics panel; save debugging remains outside release navigation."},
    {"save_migration_preview", "Save Migration Preview", "Diagnostics", EditorPanelExposure::Deferred,
     "editor/save", "Deferred diagnostics panel; save migration preview remains outside release navigation."},
    {"battle_presentation", "Battle Presentation", "Battle", EditorPanelExposure::Deferred, "editor/battle",
     "Deferred until battle presentation authoring is selected for release shell registration."},
    {"boss_designer", "Boss Designer", "Battle", EditorPanelExposure::Deferred, "editor/battle",
     "Deferred until boss design workflow is selected for release shell registration."},
    {"formula_debugger", "Formula Debugger", "Battle", EditorPanelExposure::Deferred, "editor/battle",
     "Deferred diagnostics panel; formula debugging remains outside release navigation."},
    {"battle_preview", "Battle Preview", "Battle", EditorPanelExposure::Deferred, "editor/battle",
     "Deferred until battle preview workflow is selected for release shell registration."},
    {"perf_diagnostics", "Performance Diagnostics", "Diagnostics", EditorPanelExposure::Deferred, "editor/perf",
     "Deferred diagnostics panel; performance triage remains outside release navigation."},
    {"spatial_authoring", "Spatial Authoring", "Spatial", EditorPanelExposure::Deferred, "editor/spatial",
     "Deferred until spatial authoring graduates from incubating workspace to release navigation."},
    {"elevation_brush", "Elevation Brush", "Spatial", EditorPanelExposure::Nested, "editor/spatial",
     "Rendered through SpatialAuthoringWorkspace when spatial authoring is wired."},
    {"terrain_brush", "Terrain Brush", "Spatial", EditorPanelExposure::Nested, "editor/spatial",
     "Rendered through SpatialAuthoringWorkspace when spatial authoring is wired."},
    {"region_rules", "Region Rules", "Spatial", EditorPanelExposure::Nested, "editor/spatial",
     "Rendered through SpatialAuthoringWorkspace when spatial authoring is wired."},
    {"procedural_map", "Procedural Map", "Spatial", EditorPanelExposure::Nested, "editor/spatial",
     "Rendered through SpatialAuthoringWorkspace when spatial authoring is wired."},
    {"prop_placement", "Prop Placement", "Spatial", EditorPanelExposure::Nested, "editor/spatial",
     "Rendered through SpatialAuthoringWorkspace when spatial authoring is wired."},
    {"map_ability_binding", "Map Ability Binding", "Spatial", EditorPanelExposure::Nested,
     "editor/spatial", "Rendered through SpatialAuthoringWorkspace when spatial authoring is wired."},
    {"spatial_ability_canvas", "Spatial Ability Canvas", "Spatial", EditorPanelExposure::Nested,
     "editor/spatial", "Rendered through SpatialAuthoringWorkspace when spatial authoring is wired."},
    {"sprite_animation_preview", "Sprite Animation Preview", "Content", EditorPanelExposure::Deferred,
     "editor/sprite", "Deferred until sprite animation preview is selected for release shell registration."},
    {"accessibility", "Accessibility", "Quality", EditorPanelExposure::Deferred, "editor/accessibility",
     "Deferred until accessibility settings graduate into release navigation or runtime options."},
    {"accessibility_assistant", "Accessibility Assistant", "Quality", EditorPanelExposure::Deferred,
     "editor/accessibility", "Deferred assistant workflow; accessibility automation is outside release navigation."},
    {"audio_mix", "Audio Mix", "Audio", EditorPanelExposure::Deferred, "editor/audio",
     "Deferred until audio mixing workflow is selected for release shell registration."},
    {"input_remap", "Input Remap", "Input", EditorPanelExposure::Deferred, "editor/input",
     "Deferred until editor input remapping is selected for release shell registration."},
    {"device_profile", "Device Profile", "Platform", EditorPanelExposure::Deferred, "editor/platform",
     "Deferred until platform device profiles are selected for release shell registration."},
    {"theme_builder", "Theme Builder", "UI", EditorPanelExposure::Deferred, "editor/ui",
     "Deferred until UI theme authoring is selected for release shell registration."},
    {"ai_assistant", "AI Assistant", "Productivity", EditorPanelExposure::DevOnly, "editor/ai",
     "Dev-only productivity assistant; excluded from release navigation."},
    {"local_review", "Local Review", "Collaboration", EditorPanelExposure::DevOnly, "editor/collaboration",
     "Dev-only local review tooling; excluded from release navigation."},
    {"mod_sdk", "Mod SDK", "Runtime", EditorPanelExposure::DevOnly, "editor/mod",
     "Dev-only SDK tooling for extension authors; excluded from release navigation."},
    {"core_asset_browser", "Core Asset Browser", "Core Editor", EditorPanelExposure::DevOnly,
     "engine/core/editor/panels", "Dev-only legacy core editor panel API; excluded from release navigation."},
    {"core_hierarchy", "Core Hierarchy", "Core Editor", EditorPanelExposure::DevOnly,
     "engine/core/editor/panels", "Dev-only legacy core editor panel API; excluded from release navigation."},
    {"core_property_inspector", "Core Property Inspector", "Core Editor", EditorPanelExposure::DevOnly,
     "engine/core/editor/panels", "Dev-only legacy core editor panel API; excluded from release navigation."},
};

} // namespace

const std::vector<EditorPanelRegistryEntry>& editorPanelRegistry() {
    return kRegistry;
}

std::vector<EditorPanelRegistryEntry> topLevelEditorPanels() {
    std::vector<EditorPanelRegistryEntry> panels;
    for (const auto& entry : kRegistry) {
        if (entry.exposure == EditorPanelExposure::ReleaseTopLevel) {
            panels.push_back(entry);
        }
    }
    return panels;
}

std::vector<std::string> requiredTopLevelPanelIds() {
    std::vector<std::string> ids;
    for (const auto& entry : kRegistry) {
        if (entry.exposure == EditorPanelExposure::ReleaseTopLevel) {
            ids.push_back(entry.id);
        }
    }
    return ids;
}

std::vector<std::string> smokeRequiredEditorPanelIds() {
    return requiredTopLevelPanelIds();
}

const EditorPanelRegistryEntry* findEditorPanelRegistryEntry(std::string_view id) {
    const auto it = std::find_if(kRegistry.begin(), kRegistry.end(),
                                 [id](const EditorPanelRegistryEntry& entry) { return entry.id == id; });
    return it == kRegistry.end() ? nullptr : &(*it);
}

bool hiddenEditorPanelEntriesHaveReasons() {
    return std::all_of(kRegistry.begin(), kRegistry.end(), [](const EditorPanelRegistryEntry& entry) {
        return entry.exposure == EditorPanelExposure::ReleaseTopLevel || !entry.reason.empty();
    });
}

} // namespace urpg::editor
