#include "editor/events/event_command_sequence_editor.h"
#include <algorithm>
#include <cctype>

namespace urpg::editor {
namespace {std::string lower(std::string value){std::transform(value.begin(),value.end(),value.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});return value;}}
void EventCommandSequenceEditor::load(std::vector<EventCommandSequenceRow> rows){rows_=std::move(rows);clipboard_.clear();}
std::vector<std::string> EventCommandSequenceEditor::validateNesting() const {std::vector<std::string> errors;std::vector<std::pair<urpg::events::EventCommandKind,int32_t>> stack;
    for(const auto& row:rows_){using K=urpg::events::EventCommandKind;if(row.indent<0){errors.push_back("event_indent_negative:"+row.command.id);continue;}
        if(row.command.kind==K::Condition||row.command.kind==K::Loop){if(row.indent!=static_cast<int32_t>(stack.size()))errors.push_back("event_indent_mismatch:"+row.command.id);stack.push_back({row.command.kind,row.indent});}
        else if(row.command.kind==K::ElseBranch){if(stack.empty()||stack.back().first!=K::Condition||row.indent!=stack.back().second)errors.push_back("event_else_unmatched:"+row.command.id);}
        else if(row.command.kind==K::EndBranch){if(stack.empty()||stack.back().first!=K::Condition||row.indent!=stack.back().second)errors.push_back("event_branch_unmatched:"+row.command.id);else stack.pop_back();}
        else if(row.command.kind==K::EndLoop){if(stack.empty()||stack.back().first!=K::Loop||row.indent!=stack.back().second)errors.push_back("event_loop_unmatched:"+row.command.id);else stack.pop_back();}
        else if(row.indent!=static_cast<int32_t>(stack.size()))errors.push_back("event_indent_mismatch:"+row.command.id);}
    for(const auto& [kind,indent]:stack){(void)indent;errors.push_back(kind==urpg::events::EventCommandKind::Condition?"event_branch_unclosed":"event_loop_unclosed");}return errors;}
std::vector<EventCommandSearchResult> EventCommandSequenceEditor::search(std::string query) const {query=lower(std::move(query));std::vector<EventCommandSearchResult> results;
    for(const auto& row:urpg::events::nativeEventCommandMatrix()){const bool match=query.empty()||lower(row.id).find(query)!=std::string::npos||lower(row.category).find(query)!=std::string::npos||lower(row.authoring_ui).find(query)!=std::string::npos;if(match)results.push_back({row.id,row.category,row.authoring_ui,favorites_.contains(row.id),std::find(recent_.begin(),recent_.end(),row.id)!=recent_.end()});}
    std::stable_sort(results.begin(),results.end(),[](const auto& a,const auto& b){if(a.favorite!=b.favorite)return a.favorite;if(a.recent!=b.recent)return a.recent;return a.id<b.id;});return results;}
bool EventCommandSequenceEditor::setFavorite(std::string id,bool favorite){if(std::none_of(urpg::events::nativeEventCommandMatrix().begin(),urpg::events::nativeEventCommandMatrix().end(),[&](const auto& row){return row.id==id;}))return false;if(favorite)favorites_.insert(std::move(id));else favorites_.erase(id);return true;}
bool EventCommandSequenceEditor::registerTemplate(std::string id,std::vector<EventCommandSequenceRow> rows){if(id.empty()||rows.empty()||templates_.contains(id))return false;EventCommandSequenceEditor probe;probe.load(rows);if(!probe.validateNesting().empty())return false;templates_[std::move(id)]=std::move(rows);return true;}
EventCommandEditResult EventCommandSequenceEditor::mutate(const std::function<void()>& op,size_t affected,std::string code){const auto before=rows_;op();if(!validateNesting().empty()){rows_=before;return {false,"event_edit_nesting_rejected",0};}return {true,std::move(code),affected};}
void EventCommandSequenceEditor::recordRecent(const std::string& id){recent_.erase(std::remove(recent_.begin(),recent_.end(),id),recent_.end());recent_.insert(recent_.begin(),id);if(recent_.size()>16)recent_.resize(16);}
EventCommandEditResult EventCommandSequenceEditor::insert(size_t index,EventCommandSequenceRow row){if(index>rows_.size()||row.command.id.empty())return {false,"event_insert_invalid",0};recordRecent(urpg::events::toString(row.command.kind));return mutate([&]{rows_.insert(rows_.begin()+static_cast<std::ptrdiff_t>(index),std::move(row));},1,"event_insert_applied");}
EventCommandEditResult EventCommandSequenceEditor::insertTemplate(size_t index,const std::string& id){const auto found=templates_.find(id);if(found==templates_.end()||index>rows_.size())return {false,"event_template_missing",0};auto copy=found->second;for(auto& row:copy)row.command.id+=":template:"+std::to_string(++copy_serial_);return mutate([&]{rows_.insert(rows_.begin()+static_cast<std::ptrdiff_t>(index),copy.begin(),copy.end());},copy.size(),"event_template_applied");}
EventCommandEditResult EventCommandSequenceEditor::copy(size_t first,size_t count){if(count==0||first+count>rows_.size())return {false,"event_copy_invalid",0};clipboard_.assign(rows_.begin()+static_cast<std::ptrdiff_t>(first),rows_.begin()+static_cast<std::ptrdiff_t>(first+count));return {true,"event_copy_ready",count};}
EventCommandEditResult EventCommandSequenceEditor::paste(size_t index){if(clipboard_.empty()||index>rows_.size())return {false,"event_paste_invalid",0};auto copy=clipboard_;for(auto& row:copy)row.command.id+=":copy:"+std::to_string(++copy_serial_);return mutate([&]{rows_.insert(rows_.begin()+static_cast<std::ptrdiff_t>(index),copy.begin(),copy.end());},copy.size(),"event_paste_applied");}
EventCommandEditResult EventCommandSequenceEditor::reorder(size_t first,size_t count,size_t destination){if(count==0||first+count>rows_.size()||destination>rows_.size()||(destination>=first&&destination<=first+count))return {false,"event_reorder_invalid",0};return mutate([&]{std::vector<EventCommandSequenceRow> moved(rows_.begin()+first,rows_.begin()+first+count);rows_.erase(rows_.begin()+first,rows_.begin()+first+count);if(destination>first)destination-=count;rows_.insert(rows_.begin()+destination,moved.begin(),moved.end());},count,"event_reorder_applied");}
EventCommandEditResult EventCommandSequenceEditor::multiEdit(const std::vector<size_t>& indices,std::string target,std::string value,int64_t amount){if(indices.empty()||std::any_of(indices.begin(),indices.end(),[&](size_t i){return i>=rows_.size();}))return {false,"event_multi_edit_invalid",0};return mutate([&]{for(const auto i:indices){rows_[i].command.target=target;rows_[i].command.value=value;rows_[i].command.amount=amount;}},indices.size(),"event_multi_edit_applied");}
EventCommandEditResult EventCommandSequenceEditor::keyAction(EventSequenceKeyAction action,size_t index,size_t count){if(action==EventSequenceKeyAction::Copy)return copy(index,count);if(action==EventSequenceKeyAction::Paste)return paste(index);if(index>=rows_.size())return {false,"event_keyboard_index_invalid",0};
    if(action==EventSequenceKeyAction::MoveUp)return index==0?EventCommandEditResult{false,"event_reorder_invalid",0}:reorder(index,count,index-1);
    if(action==EventSequenceKeyAction::MoveDown)return reorder(index,count,std::min(rows_.size(),index+count+1));
    if(action==EventSequenceKeyAction::Delete)return mutate([&]{rows_.erase(rows_.begin()+index,rows_.begin()+std::min(rows_.size(),index+count));},count,"event_delete_applied");
    rows_[index].collapsed=!rows_[index].collapsed;
    return {true,"event_collapse_toggled",1};
}
std::vector<EventCommandSequenceRow> EventCommandSequenceEditor::visibleRows() const {std::vector<EventCommandSequenceRow> visible;std::optional<int32_t> hiddenIndent;for(const auto& row:rows_){if(hiddenIndent&&row.indent>*hiddenIndent)continue;if(hiddenIndent&&row.indent<=*hiddenIndent)hiddenIndent.reset();visible.push_back(row);if(row.collapsed)hiddenIndent=row.indent;}return visible;}
} // namespace urpg::editor
