set(CPACK_PACKAGE_NAME "URPG")
set(CPACK_PACKAGE_VENDOR "URPG Project")
set(CPACK_PACKAGE_CONTACT "URPG Project support via GitHub Issues: https://github.com/DocDamage/URPG-RPG-Game-Designer/issues")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "URPG native runtime and editor")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/DocDamage/URPG-RPG-Game-Designer")

set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_GENERATOR "ZIP;TGZ")
set(CPACK_PACKAGE_FILE_NAME "URPG-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")

set(CPACK_COMPONENTS_ALL Runtime RuntimeData Docs)
set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "URPG applications")
set(CPACK_COMPONENT_RUNTIME_DESCRIPTION "URPG runtime, editor, audio smoke app, and required runtime DLLs.")
set(CPACK_COMPONENT_RUNTIMEDATA_DISPLAY_NAME "URPG runtime data")
set(CPACK_COMPONENT_RUNTIMEDATA_DESCRIPTION "Schemas, starter templates, readiness data, level libraries, app UI skin assets, and governed manifests.")
set(CPACK_COMPONENT_DOCS_DISPLAY_NAME "URPG documentation")
set(CPACK_COMPONENT_DOCS_DESCRIPTION "Release, legal, credits, privacy, template, and packaging documentation.")

include(CPack)
